import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "on-primary-fixed-variant": "#003ea8",
                "surface-container-highest": "#e1e2ed",
                "on-tertiary": "#ffffff",
                "status-success-bg": "#D1FAE5",
                "on-secondary": "#ffffff",
                "status-approved-text": "#075985",
                "secondary-fixed-dim": "#b9c7df",
                "on-surface": "#191b23",
                "stock-available": "#065F46",
                "on-secondary-fixed-variant": "#3a485b",
                "on-tertiary-fixed-variant": "#7d2d00",
                "inverse-primary": "#b4c5ff",
                "surface-dim": "#d9d9e5",
                "stock-limited": "#92400E",
                "primary-fixed": "#dbe1ff",
                "status-approved-bg": "#E0F2FE",
                "primary-container": "#2563eb",
                "primary": "#004ac6",
                "inverse-on-surface": "#f0f0fb",
                "on-secondary-container": "#57657a",
                "background": "#faf8ff",
                "on-surface-variant": "#434655",
                "outline": "#737686",
                "on-tertiary-fixed": "#360f00",
                "inverse-surface": "#2e3039",
                "status-rejected-text": "#9F1239",
                "outline-variant": "#c3c6d7",
                "on-primary-container": "#eeefff",
                "tertiary-container": "#bc4800",
                "surface-bright": "#faf8ff",
                "tertiary-fixed-dim": "#ffb596",
                "secondary-container": "#d5e3fc",
                "status-overdue-text": "#FFFFFF",
                "status-rejected-bg": "#FFE4E6",
                "secondary": "#515f74",
                "surface-tint": "#0053db",
                "status-pending-bg": "#FEF3C7",
                "surface-container-lowest": "#ffffff",
                "status-partial-bg": "#FFEDD5",
                "error": "#ba1a1a",
                "tertiary-fixed": "#ffdbcd",
                "status-loan-bg": "#E0E7FF",
                "stock-maintenance": "#1E293B",
                "stock-none": "#64748B",
                "on-primary-fixed": "#00174b",
                "secondary-fixed": "#d5e3fc",
                "surface": "#faf8ff",
                "on-secondary-fixed": "#0d1c2e",
                "surface-container-low": "#f3f3fe",
                "status-loan-text": "#3730A3",
                "tertiary": "#943700",
                "on-error": "#ffffff",
                "surface-container": "#ededf9",
                "error-container": "#ffdad6",
                "on-tertiary-container": "#ffede6",
                "status-overdue-bg": "#E11D48",
                "on-primary": "#ffffff",
                "primary-fixed-dim": "#b4c5ff",
                "status-pending-text": "#92400E",
                "on-error-container": "#93000a",
                "on-background": "#191b23",
                "status-partial-text": "#9A3412",
                "surface-container-high": "#e7e7f3",
                "status-success-text": "#065F46",
                "surface-variant": "#e1e2ed",
                "sidebar-dark": "#0F172A",
            },
            spacing: {
                "gutter-md": "1.5rem",
                "padding-card": "1.5rem",
                "container-max": "80rem",
                "margin-page": "1rem",
                "gutter-sm": "1rem",
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Inter', 'sans-serif'],
                'headline-md': ['Inter', 'sans-serif'],
                'headline-sm': ['Inter', 'sans-serif'],
                'title-sm': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'label-md': ['Inter', 'sans-serif'],
                'caption-xs': ['Inter', 'sans-serif'],
                'badge-xs': ['Inter', 'sans-serif'],
            },
            fontSize: {
                "badge-xs": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
                "caption-xs": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
                "headline-lg": ["30px", { "lineHeight": "36px", "fontWeight": "700" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "title-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
                "headline-sm": ["18px", { "lineHeight": "28px", "fontWeight": "600" }],
            },
        },
    },

    plugins: [forms],
};
